spring.datasource.url=jdbc:postgresql://localhost:5432/gymsystem
spring.datasource.username=postgres
spring.datasource.password=9899
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:/Y4vu8t6IdfzogjmlC0YEo34pwCb2nNRsO0LJYkfaKY=}
jwt.expiration=3600000
jwt.refresh-expiration=604800000