spring.datasource.url=jdbc:postgresql://localhost:5432/gymsystem
spring.datasource.username=postgres
spring.datasource.password=9899
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:Ys6FO=umTYl7NbXEX_=edDK-$ZkGu-TsGMKC5wOnBqvKiJLD41--TZjya06qpjVqeSHH2YkHJmEwo8leIzq06FXgRRb2GNandwi&qRtjGDTW&OH!&7vG8E_ZT89s2div_nsk1gd78IrPW3MomeGODZvs7-_7xb8juW8wIH1ihQ#2#FxphsOIHmH1cfro-0Ecwd9BC3iqvlh48WDqUMq2_ok9CiG1I16B4LhdmF2#&i1#IKpqymW$p#ovnLwpnA9IGBlOVzVwWu47nvO4ckICXnjV8iwpRplMra#&2Mnz&FjmWEubZKqTMq861OzBkdwgsa$HwJm6VBdxFK!#&1x$LRZg}
jwt.expiration=3600000
jwt.refresh-expiration=604800000